version: '3'

services:
  database:
    image: mongo:latest
    container_name: 'nodejs-final'
    environment:
      - MONGO_INITDB_DATABASE=mongo-db-test
      - MONGO_INITDB_ROOT_USERNAME=mongoUser
      - MONGO_INITDB_ROOT_PASSWORD=passw0rd
    ports:
      - 27017-27019:27017-27019
    volumes:
      - ./mongo-volume:/data/db
    restart: 'no'

  mongo-express:
    image: mongo-express
    restart: 'no'
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongoUser
      ME_CONFIG_MONGODB_ADMINPASSWORD: passw0rd
      ME_CONFIG_MONGODB_SERVER: database

